workflows:
  ios-automatic-code-signing:
    name: CiCd Dyz Test
    instance_type: mac_mini_m2
    working_directory: ios/
    integrations:
      app_store_connect: "eSparkBiz Technologies Private Limited"
    environment:
      groups:
        - cicd Megic
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.cicdmegic.app

      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        BUNDLE_ID: com.cicdmegic.app
        APP_STORE_APP_ID: 6692628444
        APP_STORE_CONNECT_API_KEY: "MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgX41ItzCIHwxuBEP7VOCSmj+Zx4yK9rybRPRLSuckG02gCgYIKoZIzj0DAQehRANCAAQ1763TfiNPWIrvBuyFiB3hK5SPsQZ2ffpc889ByvObECT5dNUxEr0dVJ2G4HhcGoZ7/d5ONUE+0yfFLfw6T3xa"
        xcode: 15.2
        FLUTTER_VERSION: "3.24.3"
      cocoapods: default
    scripts:
      - name: Install Flutter
        script: |
          git clone https://github.com/flutter/flutter.git
          cd flutter
          git checkout $FLUTTER_VERSION  # Use specified version
          export PATH="$PATH:$(pwd)/bin"
          flutter channel stable
          flutter upgrade
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Set up keychain to be used for codesigning using Codemagic CLI 'keychain' command
        script: |
          keychain initialize
          keychain add-certificates
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Fetch and increment the build number from TestFlight
        script: |
          # Fetch latest build number using App Store Connect API
          LATEST_BUILD_NUMBER=$(curl -X GET "https://api.appstoreconnect.apple.com/v1/builds?filter[appStoreVersion]=$APP_STORE_APP_ID" \
            -H "Authorization: Bearer $APP_STORE_CONNECT_API_KEY" \
            -H "Content-Type: application/json" | \
            jq '.data | max_by(.attributes.version) | .attributes.version')
          
          echo "Latest Build Number: $LATEST_BUILD_NUMBER"
          
          # Increment the build number
          NEW_BUILD_NUMBER=$((LATEST_BUILD_NUMBER + 1))
          
          echo "New Build Number: $NEW_BUILD_NUMBER"
          
          # Set the build number in pubspec.yaml
          sed -i.bak "s/\(version: [0-9]\+\.[0-9]\+\.[0-9]\+\+\)[0-9]\+/\1$NEW_BUILD_NUMBER/" pubspec.yaml
          
          # Display the updated version for confirmation
          grep "version: " pubspec.yaml
      - name: Clean build folder
        script: |
          flutter clean
          rm -rf ios/Pods
          rm -rf ios/Podfile.lock
          flutter pub get
          pod install --repo-update
      - name: Flutter build ipa
        script: |
          flutter build ipa --release \
            --build-name=1.0.0 \
            --build-number=3 \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - $CM_BUILD_DIR/build/ios/ipa/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      app_store_connect:
        #        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        #        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        #        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
      email:
        recipients:
          - iostest680@gmail.com
        notify:
          success: true
          failure: true
